mode: debug
target_frame_rate: 100
shadow_constant: 1
device: cpu
display: pygame2
use_depth_occlusion: False
window_size: [640, 360]


light_config:
  direction: [1.0, 1.0, -0.2] # it will be normalized during postprocessing
  color: [0.6, 0.8, 1.0] # rgb
  intensity_config:
    light: 5.0
    ambient: 1.5
    shadow: 0.05
  shadow_poisson_sampling_denominator: 700.0
  gamma_correction: 1.2

camera_config:
  fov: 72.0
  near: 0.1
  far: 100.0

scenario_configs:
  world:
    scenario2world:
      pos:   [0.0, -1.8, 0.0]
      rot:   [0.0, 0.0, 0.0]
      scale: [1.0, 1.0, 1.0]
  intersection:
    is_activated: True
    trigger_distance: 10.0
    npc_trajectory_type: turn_left   #choose from ["turn_left", "go_straight"]
    vehicle_type: suv
    scenario2world:
      pos:   [80.0, -1.8, -6.0]
      rot:   [0.0, 0.0, 0.0]
      scale: [1.0, 1.0, 1.0]

  jaywalking:
    is_activated: True
    trigger_distance: 10.0
    scenario2world: 
      pos:   [40.0, -1.8, -1.0]
      rot:   [0.0, 0.0, 0.0]
      scale: [1.0, 1.0, 1.0]
    actor_configs:
      actor_0:
        animation_type: woman_walking
        object2scenario: 
          pos:   [0.0, 0.0, -2.0]
          rot:   [0.0, 180, 0.0]
          scale: [1.0, 1.0, 1.0]
      

  static_objects:
    is_activated: True
    scenario2world: 
      pos:   [0.0, -1.8, 0.0]
      rot:   [0.0, 0.0, 0.0]
      scale: [1.0, 1.0, 1.0]
    object_configs:
      object_0:
        object_type: chair_0
        object2scenario: 
          pos:   [45.0, 0.0, -12.0]
          rot:   [0.0, 0.0, 0.0]
          scale: [1.0, 1.0, 1.0]
      object_1:
        object_type: chair_1
        object2scenario: 
          pos:   [35.0, 0.0, -4.0]
          rot:   [0.0, 0.0, 0.0]
          scale: [1.0, 1.0, 1.0]
      object_2:
        object_type: ladder
        object2scenario: 
          pos:   [50.0, 0.0, -7.0]
          rot:   [0.0, 0.0, 0.0]
          scale: [1.0, 1.0, 1.0]
      object_3:
        object_type: albert
        object2scenario: 
          pos:   [30.0, 0.0, -7.5]
          rot:   [0.0, 90.0, 0.0]
          scale: [1.0, 1.0, 1.0]
      object_4:
        object_type: sim_cone
        object2scenario: 
          pos:   [45.0, 0.0, -3.0]
          rot:   [0.0, 0.0, 0.0]
          scale: [1.0, 1.0, 1.0]
      object_5:
        object_type: zhi-hao
        object2scenario: 
          pos:   [45.0, 0.0, -7.0]
          rot:   [0.0, 90.0, 0.0]
          scale: [1.0, 1.0, 1.0]
