mode: debug
target_frame_rate: 10
shadow_constant: 1
device: cpu
display: pygame2
use_depth_occlusion: False
window_size:  [1408, 376]
name: '1578-1598-ped-cone2'

kitti:
  frame_start: 1978
  frame_end:   1998

light_config:
  direction: [0.8, 1.0, 0.3] # it will be normalized during postprocessing
  color: [0.6, 0.8, 1.0] # rgb
  intensity_config:
    light: 5.0
    ambient: 0.3
    shadow: 0.08
  shadow_poisson_sampling_denominator: 700.0
  gamma_correction: 1.2

camera_config:
  fov: 72
  near: 0.1
  far: 100.0

scenario_configs:
  world:
    scenario2world:
      pos:   [0.0, -5, 0.0]
      rot:   [0.0, 0.0, 0.0]
      scale: [1.0, 1.0, 1.0]
  intersection:
    is_activated: False
    trigger_distance: 35.0
    npc_trajectory_type: turn_left   #choose from ["turn_left", "go_straight"]
    vehicle_type: suv
    scenario2world:
      pos:   [80.0, -1.8, -6.0]
      rot:   [0.0, 0.0, 0.0]
      scale: [1.0, 1.0, 1.0]

  jaywalking:
    is_activated: True
    trigger_distance: 10.0
    scenario2world: 
      pos:   [0, -5.0, 0.0]
      rot:   [0.0, 0.0, 0.0]
      scale: [1.0, 1.0, 1.0]
    actor_configs:
      actor_0:
        animation_type: woman_walking
        object2scenario: 
          pos:   [-1.0, -5.0, 5.0]
          rot:   [0.0, 180, 0.0]
          scale: [2.5, 2.5, 2.5]
      actor_1:
        animation_type: man_running
        object2scenario: 
          pos:   [-4.0, 0.0, 3.0]
          rot:   [0.0, -90, 0.0]
          scale: [2.5, 2.5, 2.5]
      

  static_objects:
    is_activated: False
    scenario2world: 
      pos:   [0.0, -5.0, 0.0]
      rot:   [0.0, 0.0, 0.0]
      scale: [1.0, 1.0, 1.0]
    object_configs:
      object_0:
        object_type: sim_cone
        object2scenario: 
          pos:   [-12.0, 0.0, 2.5]
          rot:   [0.0, 0.0, 0.0]
          scale: [3.0, 3.0, 3.0]