mode: debug
target_frame_rate: 100
shadow_constant: 1
device: cpu
display: pygame2
use_depth_occlusion: False
window_size: [640, 360]


light_config:
  direction: [1.0, 1.0, 0.0] # it will be normalized during postprocessing
  color: [0.6, 0.8, 1.0] # rgb
  intensity_config:
    light: 3.0
    ambient: 0.5
    shadow: 0.02
  shadow_poisson_sampling_denominator: 700.0
  gamma_correction: 1.2

camera_config:
  fov: 72.0
  near: 0.1
  far: 100.0

scenario_configs:
  world:
    scenario2world:
      pos:   [100.0, -1.8, 0.0]
      rot:   [0.0, 0.0, 0.0]
      scale: [3.0, 1.0, 3.0]
  intersection:
    is_activated: False
    trigger_distance: 35.0
    npc_trajectory_type: turn_left   #choose from ["turn_left", "go_straight"]
    vehicle_type: suv
    scenario2world:
      pos:   [80.0, -1.8, -6.0]
      rot:   [0.0, 0.0, 0.0]
      scale: [1.0, 1.0, 1.0]

  jaywalking:
    is_activated: True
    trigger_distance: 5.0
    scenario2world: 
      pos:   [165.0, -1.8, 0.0]
      rot:   [0.0, 0.0, 0.0]
      scale: [1.0, 1.0, 1.0]
    actor_configs:
      actor_0:
        animation_type: woman_walking
        object2scenario: 
          pos:   [-2.0, 0.0, 18.0]
          rot:   [0.0, 90, 0.0]
          scale: [1.0, 1.0, 1.0]
      actor_1:
        animation_type: man_running
        object2scenario: 
          pos:   [2.0, 0.0, 15.0]
          rot:   [0.0, -90, 0.0]
          scale: [1.0, 1.0, 1.0]
      

  static_objects:
    is_activated: True
    scenario2world: 
      pos:   [160.0, -1.8, 0.0]
      rot:   [0.0, 0.0, 0.0]
      scale: [1.0, 1.0, 1.0]
    object_configs:
      object_0:
        object_type: sim_cone
        object2scenario: 
          pos:   [0.0, 0.0, 0.0]
          rot:   [0.0, 0.0, 0.0]
          scale: [1.0, 1.0, 1.0]
