from .car import CarObject
from .traffic_light import TrafficLightObject
from .world_plane import WorldPlaneObject
from .world_building import WorldBuildingObject
from .person import PersonObject
from .cone import ConeObject
from .scanned import ScannedObject
from .baby import BabyObject
from .benz import BenzObject
from .bus import BusObject
from .building import BuildingObject
